import _ from 'lodash'

const SERVICE_2_SNAKE_CASE_MAPPING = {
  ACM: "ACM",
  ALEXAAPPKIT: "ALEXA_APPKIT",
  API_GATEWAY: "API_GATEWAY",
  APPLICATION_AUTOSCALING: "APPLICATION_AUTOSCALING",
  APP_STREAM: "APP_STREAM",
  APP_SYNC: "APP_SYNC",
  ATHENA: "ATHENA",
  AUTO_SCALING: "AUTO_SCALING",
  BATCH: "BATCH",
  CHANNELS: "CHANNELS",
  CLOUD_9: "CLOUD_9",
  CLOUD_DIRECTORY: "CLOUD_DIRECTORY",
  CLOUD_FORMATION: "CLOUD_FORMATION",
  CLOUD_FRONT: "CLOUD_FRONT",
  CLOUD_SEARCH: "CLOUD_SEARCH",
  CLOUD_TRAIL: "CLOUD_TRAIL",
  CODE_BUILD: "CODE_BUILD",
  CODE_COMMIT: "CODE_COMMIT",
  CODE_DEPLOY: "CODE_DEPLOY",
  CODE_PIPELINE: "CODE_PIPELINE",
  CONFIG: "CONFIG",
  CONTINUOUS_EXPORT: "CONTINUOUS_EXPORT",
  CUSTOM_RESOURCE: "CUSTOM_RESOURCE",
  DATA_PIPELINE: "DATA_PIPELINE",
  DAX: "DAX",
  DEEP_LENS: "DEEP_LENS",
  DIRECT_CONNECT: "DIRECT_CONNECT",
  DLM: "DLM",
  DMS: "DMS",
  DS: "DS",
  DYNAMO_DB: "DYNAMO_DB",
  EC2: "EC2",
  EC2_FLEET: "EC2_FLEET",
  EC2_SCHEDULED: "EC2_SCHEDULED",
  ECR: "ECR",
  ECS_TASKS: "ECS_TASKS",
  ECS: "ECS",
  EDGE_LAMBDA: "EDGE_LAMBDA",
  EKS: "EKS",
  ELASTI_CACHE: "ELASTI_CACHE",
  ELASTIC_BEANSTALK: "ELASTIC_BEANSTALK",
  ELASTIC_FILE_SYSTEM: "ELASTIC_FILE_SYSTEM",
  ELASTIC_LOAD_BALANCING: "ELASTIC_LOAD_BALANCING",
  ELASTIC_MAP_REDUCE: "ELASTIC_MAP_REDUCE",
  ELASTIC_TRANSCODER: "ELASTIC_TRANSCODER",
  ES: "ES",
  EVENTS: "EVENTS",
  FIREHOSE: "FIREHOSE",
  GLUE: "GLUE",
  GREENGRASS: "GREENGRASS",
  GUARDDUTY: "GUARDDUTY",
  HEALTH: "HEALTH",
  IAM: "IAM",
  INSPECTOR: "INSPECTOR",
  IOT: "IOT",
  KINESIS: "KINESIS",
  KINESIS_ANALYTICS: "KINESIS_ANALYTICS",
  KMS: "KMS",
  LAMBDA: "LAMBDA",
  LEX: "LEX",
  LIGHTSAIL: "LIGHTSAIL",
  LOGS: "LOGS",
  MACHINE_LEARNING: "MACHINE_LEARNING",
  MACIE: "MACIE",
  MEDIA_CONVERT: "MEDIA_CONVERT",
  MONITORING: "MONITORING",
  OPS_WORKS: "OPS_WORKS",
  ORGANIZATIONS: "ORGANIZATIONS",
  RDS: "RDS",
  REDSHIFT: "REDSHIFT",
  REKOGNITION: "REKOGNITION",
  REPLICATION: "REPLICATION",
  ROUTE_53: "ROUTE_53",
  S3: "S3",
  SAGE_MAKER: "SAGE_MAKER",
  SECRETS_MANAGER: "SECRETS_MANAGER",
  SERVICE_CATALOG: "SERVICE_CATALOG",
  SES: "SES",
  SIGNIN: "SIGNIN",
  SMS: "SMS",
  SNS: "SNS",
  SPOT_FLEET: "SPOT_FLEET",
  SQS: "SQS",
  SSM: "SSM",
  SSO: "SSO",
  STATES: "STATES",
  STORAGE_GATEWAY: "STORAGE_GATEWAY",
  STS: "STS",
  SUPPORT: "SUPPORT",
  SWF: "SWF",
  TRUSTED_ADVISOR: "TRUSTED_ADVISOR",
  VMIE: "VMIE",
  WAF: "WAF",
  WORK_DOCS: "WORK_DOCS",
  WORK_SPACES: "WORK_SPACES",
}

export function service2SnakeCase({service}: {
  service: string
}): string {
  return ""
}

/**
 * Normalize service name to snake case uppercase
 */
export function normalizeServiceName(name: string): string {
  const blacklist = ['S_3', 'EC_2', 'IO_T', 'V_2', 'F_S', 'AP_I']
  let modKey = _.snakeCase(name).toUpperCase()
  blacklist.forEach( ent => {
    if (modKey.indexOf(ent) >= 0) {
      modKey = modKey.replace(ent, ent.replace('_', ''))
    }
  })
  return modKey
}
